version: "3.8"

services:
  client:
    container_name: taska_client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/client"
      - "/client/node_modules"
    restart: always
    tty: true
    command: ["npm", "start"]
