version: "3.8"

services:
  client:
    build:
      args:
        APP_DIR: "app"
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start"]
    container_name: taska
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: unless-stopped
    tty: true
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
